@port = 3000
@host = localhost
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImNvbXBhbnlfaWQiOm51bGwsInJvbGVzIjpbXSwiaWF0IjoxNzY2MTc0NDQ4LCJleHAiOjE3NjYxNzUzNDh9.hsGdrr6mr8HG_pz1eZ3CVomZDfMdIyZFM6f68JpWiVY

GET http://{{host}}:{{port}}/roles/2
content-type: application/json
Authorization: Bearer {{token}}
###

POST http://{{host}}:{{port}}/roles
content-type: application/json

{
  "name": "Vendedor"
}


###
PUT  http://{{host}}:{{port}}/roles/5
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "samples"
}

###
DELETE  http://{{host}}:{{port}}/roles/5
content-type: application/json
Authorization: Bearer {{token}}

###
GET http://{{host}}:{{port}}/roles/6/permissions
content-type: application/json
Authorization: Bearer {{token}}

###
PUT http://{{host}}:{{port}}/roles/6/permissions
content-type: application/json

{
  "permissions": [12, 16]
}
