@port = 3000
@host = localhost
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImNvbXBhbnlfaWQiOm51bGwsInJvbGVzIjpbXSwiaWF0IjoxNzY2MTc0NDQ4LCJleHAiOjE3NjYxNzUzNDh9.hsGdrr6mr8HG_pz1eZ3CVomZDfMdIyZFM6f68JpWiVY

content-type: application/json
Authorization: Bearer {{token}}
###
GET http://{{host}}:{{port}}/activation/
{

}
###

GET http://{{host}}:{{port}}/users/
content-type: application/json
Authorization: Bearer {{token}}
###
POST http://{{host}}:{{port}}/users
content-type: application/json

{
  "name": "David Luis da Siva",
  "phone_number": "32 987075868",
  "date_of_birth": "1983-06-19",
  "email": "tecnicoroot5@gmail.com",
  "password": "12345678",
  "passwordConfirmation" : "12345678"

}

###
POST http://{{host}}:{{port}}/users/without
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "teste com id empresa",
  "phone_number": "11999999999",
  "date_of_birth": "1990-01-01",
  "email": "joao1emresa1005@example.com",
  "id_empresa" : 1
}

###
PUT  http://{{host}}:{{port}}/users/3
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "samples",
  "email": "sample@sample.com",
  "date_of_birth": "1",
  "password": "12345678",
  "passwordConfirmation" : "12345678",
  "oldPassword": "1"

}

###
DELETE  http://{{host}}:{{port}}/users/4l
content-type: application/json
Authorization: Bearer {{token}}

###


GET http://{{host}}:{{port}}/users/1/roles
content-type: application/json
Authorization: Bearer {{token}}
/users/:id/roles

##
###
PUT  http://{{host}}:{{port}}/users/6/roles
content-type: application/json
Authorization: Bearer {{token}}

{
  "roles": []
}