@port = 3000
@host = localhost
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidHlwZV9hY2Nlc3MiOiJDb2xhYm9yYWRvciIsInBlcm1pc3Npb25zIjpbImNyZWF0ZV91c2VyIiwicmVhZF91c2VyIiwicmVhZF9wZXJtaXNzaW9uIl0sInJvbGVzIjpbIkdlcmVudGUiXSwiaWF0IjoxNzc0NjEyNDI1LCJleHAiOjE3NzQ2MTMzMjV9.e6E5rHXY_ZbCtx_1qj9Lil7m7Y6sSUFYaoeV9UQmDoE

Authorization: Bearer {{token}}
###
GET http://{{host}}:{{port}}/activation/
{

}
###

GET http://{{host}}:{{port}}/users/
content-type: application/json
Authorization: Bearer {{token}}
###
POST http://{{host}}:{{port}}/users
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "David 101",
  "phone_number": "32 987075868",
  "date_of_birth": "1983-06-19",
  "email": "tecnicoroot8@gmail.com",
  "password": "12345678",
  "passwordConfirmation" : "12345678"

}

###
POST http://{{host}}:{{port}}/users/without
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "teste com id empresa",
  "phone_number": "11999999999",
  "date_of_birth": "1990-01-01",
  "email": "joao1emresa1005@example.com",
  "id_empresa" : 1
}

###
PUT  http://{{host}}:{{port}}/users/3
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "samples",
  "email": "sample@sample.com",
  "date_of_birth": "1",
  "password": "12345678",
  "passwordConfirmation" : "12345678",
  "oldPassword": "1"

}

###
DELETE  http://{{host}}:{{port}}/users/4l
content-type: application/json
Authorization: Bearer {{token}}

###


GET http://{{host}}:{{port}}/users/4/roles
content-type: application/json
Authorization: Bearer {{token}}


##
###
PUT  http://{{host}}:{{port}}/users/4/roles
content-type: application/json
Authorization: Bearer {{token}}

{
  "roles": [6]
}